/*=============================================================================================================== *
 * Copyright 2025 Infosys Ltd.                                                                                    *
 * Use of this source code is governed by Apache License Version 2.0 that can be found in the LICENSE file or at  *
 * http://www.apache.org/licenses/                                                                                *
 * ===============================================================================================================*/
// Copyright 2004, Microsoft Corporation
// Sample Code - Use restricted to terms of use defined in the accompanying license agreement (EULA.doc)

//--------------------------------------------------------------
// Autogenerated by XSDObjectGen version 1.4.1.0
// Schema file: LISettings.xsd
// Creation Date: 5/22/2012 2:51:09 PM
//--------------------------------------------------------------

using System;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Collections.Generic;

namespace Infosys.Lif.LegacyIntegratorService
{
    public class Region
    {
        public string Name { get; set; }
        public string TransportMedium { get; set; }
        public string TransportName { get; set; }
        public string CommunicationType { get; set; }

    }
    public class HostRegion
    {
        public IList<Region> Region { get; set; }

    }
    public class IISDocDetails
    {
        public string TransportName { get; set; }
        public int DataBlockSizeInKB { get; set; }
        public string DocumentsVirtualDirectoryFromRoot { get; set; }

    }
    public class IISDoc
    {
        public string DllPath { get; set; }
        public string TypeName { get; set; }
        public IList<IISDocDetails> IISDocDetails { get; set; }

    }
    public class MSMQDetails
    {
        public string TransportName { get; set; }
        public string ServerName { get; set; }
        public string QueueName { get; set; }
        public string PoisonQueueName { get; set; }
        public string MessageLabel { get; set; }
        public string QueueType { get; set; }
        public string QueueReadingType { get; set; }
        public string QueueReadingMode { get; set; }
        public int MessageProcessingMaxCount { get; set; }
        public bool ReadAndDelete { get; set; }
        public int MessaseInvisibilityTimeout { get; set; }
        public int QueueReadTimeout { get; set; }
        public int PollingRestDuration { get; set; }
        public bool ContinueToReceive { get; set; }
        public string SendPattern { get; set; }
        public string SecondaryQueues { get; set; }
        public int QueueLoadLimit { get; set; }
        public int TransactionWaitTime { get; set; }

    }
    public class MemoryQueueDetails
    {
        public string TransportName { get; set; }
        public string QueueName { get; set; }
        public string MessageLabel { get; set; }
        public string QueueReadingType { get; set; }
        public string QueueReadingMode { get; set; }
        public int MessageProcessingMaxCount { get; set; }
        public bool ReadAndDelete { get; set; }
        public int MessaseInvisibilityTimeout { get; set; }
        public int QueueReadTimeout { get; set; }
        public int PollingRestDuration { get; set; }
        public bool ContinueToReceive { get; set; }
        public string SendPattern { get; set; }
        public string SecondaryQueues { get; set; }
        public int QueueLoadLimit { get; set; }
        public int TransactionWaitTimeInMins { get; set; }
        public int ParallelProcessingLimit { get; set; }

    }
    public class MSMQ
    {
        public string DllPath { get; set; }
        public string TypeName { get; set; }
        public IList<MSMQDetails> MSMQDetails { get; set; }

    }
    public class MemoryQueue
    {
        public string DllPath { get; set; }
        public string TypeName { get; set; }
        public IList<MemoryQueueDetails> MemoryQueueDetails { get; set; }

    }
    
    public class MemoryDoc
    {
        public string DllPath{get;set;}

        public string TypeName{get;set;}

        public IList<MemoryDocDetails> MemoryDocDetails { get; set; }        
    }

    public class MemoryDocDetails
    {

        public string TransportName { get; set; }        
        public int DataBlockSizeInKB { get; set; }        
        public string DocumentsVirtualDirectoryFromRoot { get; set; }        
        public double MemoryCacheSlidingExpirationInMins { get; set; }
        public int  ExpirationTriggerCount { get; set; }
        public int MemoryControlMode { get; set; }
        public int CacheMemoryLimitBytes  { get; set; }
        public int PhysicalMemoryLimitPrctg { get; set; }
        public int CachePollingIntervalInSec { get; set; }
    }
    public class LISettings
    {
        public HostRegion HostRegion { get; set; }
        public IISDoc IISDoc { get; set; }
        public MSMQ MSMQ { get; set; }
        public MemoryQueue MemoryQueue { get; set; }
        public MemoryDoc MemoryDoc { get; set; }
        public Kafka Kafka { get; set; }
        public AWSS3Doc AWSS3Doc { get; set; }
        public RabbitMQAdapter RabbitMQAdapter { get; set; }

        public AzureIoTAdapter AzureIoTAdapter { get; set; }
        public AzureVault AzureVault { get; set; }
        public AWSSecrets AWSSecrets { get; set; }
    }

    public class Kafka
    {
        public string DllPath { get; set; }
        public string TypeName { get; set; }
        public IList<KafkaDetails> KafkaDetails { get; set; }
    }

    public class KafkaDetails
    {
        public string TransportName { get; set; }
        public string BootstrapServer { get; set; }
        public string TopicName { get; set; }
        public string GroupId { get; set; }
        public string SecurityProtocol { get; set; }
        public string SaslMechanism { get; set; }
        public string SaslUsername { get; set; }
        public string SaslPassword { get; set; }
        public string AutoOffsetReset { get; set; }
        public int PollingRestDurationMs { get; set; }
        public int MessageSendMaxRetries { get; set; }
        public int RetryBackoffMs { get; set; }

        public bool EnableIdempotence { get; set; }
        public bool EnableAutoCommit { get; set; }
        public bool EnableAutoOffsetStore { get; set; }
        public short ReplicationFactor { get; set; }
        public short NumPartitions { get; set; }

        public string ProducerMode { get; set; }
        public string ConsumerMode { get; set; }
        public int ConsumerConnectionRetryCount { get; set; }
        public int ConsumerConnectionRetryWait { get; set; }

    }

    public class AWSS3Doc
    {
        public string DllPath { get; set; }
        public string TypeName { get; set; }
        public IList<AWSS3DocDetails> AWSS3DocDetails { get; set; }
    }

    public class AWSS3DocDetails
    {
        public string TransportName { get; set; }
        public string Accesskey { get; set; }
        public string SecretKey { get; set; }
        public string SessionToken { get; set; }
        public string BucketName { get; set; }
        public string RegionName { get; set; }
        //public string DestinationBucketName { get; set; }
        //public string DestinationS3Path { get; set; }
        //public string LocalDestinationPath { get; set; }
        ////public string Devices { get; set; }
        ////public int IntervalForCheckingFilesInS3 { get; set; }
        //public Boolean DownloadToLocal { get; set; }
        public string AWSDirectory { get; set; }
        public string TargetRegion { get; set; }
        public int WaitTimeForFolderDelete { get; set; }
        public string LocalPath { get; set; }
        public int TokenValidityInSeconds { get; set; }
        public int FileReadIntervalInSeconds { get; set; }
        public int FileCopyIntervalInSeconds { get; set; }
        public int RetryLimit { get; set; }
        public int RetryWaitTime { get; set; }
        public int TokenRefreshTimeBeforeExpiry { get; set; }
        //public string SubStringInVideoFile { get; set; }
        //public string KeyName { get; set; } // file name to delete file
        //public string FilePath { get; set; }    //file path for file to upload
        //public string objectName { get; set; } //file to upload
    }

    //Added to Message Adapter for RabbitMQ

    public class RabbitMQAdapter
    {
        public string DllPath { get; set; }
        public string TypeName { get; set; }
        public IList<MessageDetails> MessageDetails { get; set; }
    }

    public class MessageDetails
    {
        public string TransportName { get; set; } //Supported Protocols MQTT,AMQP,HTTP
        public string ConnectionString { get; set; }
        public string DeviceName { get; set; }
        public string RegionName { get; set; }
        //Properties for RabbitMQ server.
        public string HostName { get; set; }
        public string Port { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string VirtualHost { get; set; }
        public string ContinuationTimeout { get; set; }

        public string TransportType { get; set; } // Specifies the transport mode e.g Azure Iot Hud, RabbitMQ . etc
        public string QueueName { get; set; }

        public string TopicName { get; set; }
        public string RoutingKey { get; set; }

    }


    public class AzureIoTAdapter
    {
        public string DllPath { get; set; }
        public string TypeName { get; set; }
        public IList<AzureIoTDetails> AzureIoTDetails { get; set; }
    }
    public class AzureIoTDetails
    {
        public string TransportName { get; set; } //Supported Protocols MQTT,AMQP,HTTP
        public string IoTConnectionString { get; set; }
        public string QueueConnectionString { get; set; }
        public string DeviceName { get; set; }
        public string RegionName { get; set; }

        public string TransportType { get; set; } // Specifies the transport mode e.g Azure Iot Hud, RabbitMQ . etc
        public string ServiceBusQueueName { get; set; }

    }

    public class AzureVault
    {
        public string DllPath { get; set; }
        public string TypeName { get; set; }
        public IList<AzureVaultDetails> AzureVaultDetails { get; set; }
    }

    public class AzureVaultDetails
    {
        public string TransportName { get; set; }
        public string VaultName { get; set; }
        public string VaultUrl { get; set; }
        public int Delay { get; set; }
        public int MaxDelay { get; set; }
        public int MaxRetries { get; set; }
        public string CertificatePath { get; set; } 
        public string TenantId { get; set; }
        public string ClientId { get; set; }
    }


    public class AWSSecrets
    {
        public string DllPath { get; set; }
        public string TypeName { get; set; }
        public IList<AWSSecretsDetails> AWSSecretsDetails { get; set; }
    }

    public class AWSSecretsDetails
    {
        public string TransportName { get; set; }
        public string VersionStage { get; set; }
        public string Region { get;set; }
        public int Retry { get; set; }
    }

}
