/*=============================================================================================================== *
 * Copyright 2025 Infosys Ltd.                                                                                    *
 * Use of this source code is governed by Apache License Version 2.0 that can be found in the LICENSE file or at  *
 * http://www.apache.org/licenses/                                                                                *
 * ===============================================================================================================*/
﻿//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infosys.Solutions.Ainauto.VideoAnalytics.Infrastructure.ComputerVisionLib.Logging {
    using System;
    
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class InformationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InformationMessages() {
        }
        
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ComputerVisionLib.Logging.InformationMessages", typeof(InformationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
       
        internal static string RUNTIMEWRAPPER_ENTER {
            get {
                return ResourceManager.GetString("RUNTIMEWRAPPER_ENTER", resourceCulture);
            }
        }
        
       
        internal static string RUNTIMEWRAPPER_EXIT {
            get {
                return ResourceManager.GetString("RUNTIMEWRAPPER_EXIT", resourceCulture);
            }
        }
        
        
        internal static string RUNTIMEWRAPPER_INVALID_DATA {
            get {
                return ResourceManager.GetString("RUNTIMEWRAPPER_INVALID_DATA", resourceCulture);
            }
        }
        
        
        internal static string RUNTIMEWRAPPER_PARAMETERS {
            get {
                return ResourceManager.GetString("RUNTIMEWRAPPER_PARAMETERS", resourceCulture);
            }
        }
        
        
        internal static string RUNTIMEWRAPPER_ReadTextAreaFailure {
            get {
                return ResourceManager.GetString("RUNTIMEWRAPPER_ReadTextAreaFailure", resourceCulture);
            }
        }
        
        
        internal static string RUNTIMEWRAPPER_VARIABLE_VALUE {
            get {
                return ResourceManager.GetString("RUNTIMEWRAPPER_VARIABLE_VALUE", resourceCulture);
            }
        }
    }
}
