/*=============================================================================================================== *
 * Copyright 2024 Infosys Ltd.                                                                                    *
 * Use of this source code is governed by Apache License Version 2.0 that can be found in the LICENSE file or at  *
 * http://www.apache.org/licenses/                                                                                *
 * ===============================================================================================================*/

﻿//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infosys.Solutions.Ainauto.VideoAnalytics.Infrastructure.Common {
    using System;
    
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class InfoMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InfoMessages() {
        }
        
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Infosys.Solutions.Ainauto.VideoAnalytics.Infrastructure.Common.InfoMessages", typeof(InfoMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        
        public static string Attachment_FileName {
            get {
                return ResourceManager.GetString("Attachment_FileName", resourceCulture);
            }
        }
        
       
        public static string EMAIL_SUBJECT_ANOMALY_DETECTED {
            get {
                return ResourceManager.GetString("EMAIL_SUBJECT_ANOMALY_DETECTED", resourceCulture);
            }
        }
        
       
        public static string EMAIL_SUBJECT_ENVIRONMENT_SCAN {
            get {
                return ResourceManager.GetString("EMAIL_SUBJECT_ENVIRONMENT_SCAN", resourceCulture);
            }
        }
        
       
        public static string EMAIL_SUBJECT_ENVIRONMENT_SCAN_CONSOLIDATED {
            get {
                return ResourceManager.GetString("EMAIL_SUBJECT_ENVIRONMENT_SCAN_CONSOLIDATED", resourceCulture);
            }
        }
        
        
        public static string EMAIL_SUBJECT_NO_REMEDIATION {
            get {
                return ResourceManager.GetString("EMAIL_SUBJECT_NO_REMEDIATION", resourceCulture);
            }
        }
        
        
        public static string EMAIL_SUBJECT_REMEDIATION_FAILURE {
            get {
                return ResourceManager.GetString("EMAIL_SUBJECT_REMEDIATION_FAILURE", resourceCulture);
            }
        }
        
       
        public static string EMAIL_SUBJECT_REMEDIATION_SUCCESS {
            get {
                return ResourceManager.GetString("EMAIL_SUBJECT_REMEDIATION_SUCCESS", resourceCulture);
            }
        }
        
       
        public static string EMAIL_SUBJECT_REMEDIATION_SUCCESS_ATTACHMENT {
            get {
                return ResourceManager.GetString("EMAIL_SUBJECT_REMEDIATION_SUCCESS_ATTACHMENT", resourceCulture);
            }
        }
        
       
        public static string EMAIL_SUBJECT_SUMMARY {
            get {
                return ResourceManager.GetString("EMAIL_SUBJECT_SUMMARY", resourceCulture);
            }
        }
        
       
        public static string EMAIL_SUBJECT_THRESHOLD_BREACH {
            get {
                return ResourceManager.GetString("EMAIL_SUBJECT_THRESHOLD_BREACH", resourceCulture);
            }
        }
        
       
        public static string Final_Body {
            get {
                return ResourceManager.GetString("Final_Body", resourceCulture);
            }
        }
        
       
        public static string Installed_Software_Body {
            get {
                return ResourceManager.GetString("Installed_Software_Body", resourceCulture);
            }
        }
        
       
     
        public static string Installed_Software_Row {
            get {
                return ResourceManager.GetString("Installed_Software_Row", resourceCulture);
            }
        }
        
        
        public static string Method_Execution_End {
            get {
                return ResourceManager.GetString("Method_Execution_End", resourceCulture);
            }
        }
        
       
        public static string Method_Execution_Start {
            get {
                return ResourceManager.GetString("Method_Execution_Start", resourceCulture);
            }
        }
        
       
        public static string OSDetails_Body {
            get {
                return ResourceManager.GetString("OSDetails_Body", resourceCulture);
            }
        }
        
       
        public static string OSDetails_Row {
            get {
                return ResourceManager.GetString("OSDetails_Row", resourceCulture);
            }
        }
        
        
        public static string SR_Body {
            get {
                return ResourceManager.GetString("SR_Body", resourceCulture);
            }
        }
        
       
        public static string SR_Row {
            get {
                return ResourceManager.GetString("SR_Row", resourceCulture);
            }
        }
        
       
        public static string SummaryNotiffication_Body {
            get {
                return ResourceManager.GetString("SummaryNotiffication_Body", resourceCulture);
            }
        }
        
       
        public static string SummaryNotification_Row {
            get {
                return ResourceManager.GetString("SummaryNotification_Row", resourceCulture);
            }
        }
    }
}
