/*=============================================================================================================== *
 * Copyright 2025 Infosys Ltd.                                                                                    *
 * Use of this source code is governed by Apache License Version 2.0 that can be found in the LICENSE file or at  *
 * http://www.apache.org/licenses/                                                                                *
 * ===============================================================================================================*/
﻿//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common {
    using System;
    
    
   
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource2 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource2() {
        }
        
       
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Common.Resource2", typeof(Resource2).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
       
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
       
        internal static string Attachment_FileName {
            get {
                return ResourceManager.GetString("Attachment_FileName", resourceCulture);
            }
        }
        
       
        internal static string EMAIL_SUBJECT_ANOMALY_DETECTED {
            get {
                return ResourceManager.GetString("EMAIL_SUBJECT_ANOMALY_DETECTED", resourceCulture);
            }
        }
        
       
        internal static string EMAIL_SUBJECT_ENVIRONMENT_SCAN {
            get {
                return ResourceManager.GetString("EMAIL_SUBJECT_ENVIRONMENT_SCAN", resourceCulture);
            }
        }
        
        
        internal static string EMAIL_SUBJECT_ENVIRONMENT_SCAN_CONSOLIDATED {
            get {
                return ResourceManager.GetString("EMAIL_SUBJECT_ENVIRONMENT_SCAN_CONSOLIDATED", resourceCulture);
            }
        }
        
       
        internal static string EMAIL_SUBJECT_NO_REMEDIATION {
            get {
                return ResourceManager.GetString("EMAIL_SUBJECT_NO_REMEDIATION", resourceCulture);
            }
        }
        
       
        internal static string EMAIL_SUBJECT_REMEDIATION_FAILURE {
            get {
                return ResourceManager.GetString("EMAIL_SUBJECT_REMEDIATION_FAILURE", resourceCulture);
            }
        }
        
       
        internal static string EMAIL_SUBJECT_REMEDIATION_SUCCESS {
            get {
                return ResourceManager.GetString("EMAIL_SUBJECT_REMEDIATION_SUCCESS", resourceCulture);
            }
        }
        
        
        internal static string EMAIL_SUBJECT_REMEDIATION_SUCCESS_ATTACHMENT {
            get {
                return ResourceManager.GetString("EMAIL_SUBJECT_REMEDIATION_SUCCESS_ATTACHMENT", resourceCulture);
            }
        }
        
       
        internal static string EMAIL_SUBJECT_SUMMARY {
            get {
                return ResourceManager.GetString("EMAIL_SUBJECT_SUMMARY", resourceCulture);
            }
        }
        
       
        internal static string EMAIL_SUBJECT_THRESHOLD_BREACH {
            get {
                return ResourceManager.GetString("EMAIL_SUBJECT_THRESHOLD_BREACH", resourceCulture);
            }
        }
    }
}
